<?php

declare(strict_types=1);

namespace App\Dashboard;

use App\Tenancy\TenantScope;
use PDO;
use PDOStatement;
use UnexpectedValueException;

/**
 * Read model for the operations dashboard (P1-T15: FR-DASH-001/002,
 * LFR-DASH-001/002/003).
 *
 * SECURITY (AC-001 / FR-TEN-002): every query is tenant-scoped through
 * App\Tenancy\TenantScope. The tenant predicate and value are generated and
 * bound by TenantScope - never interpolated, never caller-overridable - so a
 * tenant can only read its own aggregation. This class uses PDO::prepare() +
 * TenantScope::bindTo(), which is the sanctioned path the PHPStan
 * NoUnscopedClientQueryRule leaves open (it forbids raw query()/exec(), not
 * prepared, scoped statements).
 *
 * WHY A DEDICATED READ MODEL, NOT THE EXISTING REPOSITORIES: the dashboard
 * needs cross-table aggregates (lead status counts, pending AI analyses,
 * failed deliveries) that no single-entity repository exposes. The aggregates
 * are read-only and tenant-scoped; they add no write surface.
 *
 * THE FIVE LEAD STATES ARE THE SOURCE OF TRUTH. migration/005_leads.sql defines
 * leads.status as ENUM('New','Review','Qualified','Disqualified','Converted').
 * The pipeline exposed here is exactly those five - the plan's older 10-state
 * sketch was never implemented in T5-T12, and this task does not mutate the
 * domain model (see docs/SESSION_HANDOFF_P1T14.md deviation log). When the
 * platform later grows the pipeline, this constant widens in lockstep with the
 * schema, not before it.
 *
 * © AI WebScapes 2026
 */
final class DashboardRepository
{
    /**
     * The complete, ordered lead lifecycle as it actually exists in the schema.
     * Order is load-bearing for the dashboard pipeline view (LFR-DASH-001).
     *
     * @var list<string>
     */
    public const LEAD_STATES = ['New', 'Review', 'Qualified', 'Disqualified', 'Converted'];

    public function __construct(private PDO $pdo, private int $tenantId)
    {
        // Validates the tenant up front: a DashboardRepository for a null/zero/
        // negative tenant cannot be constructed, so every read it performs is
        // already bound to a real tenant (mirrors TenantScope's construction
        // gate, duplicated here because we hold the PDO directly rather than
        // extending the abstract TenantRepository).
        new TenantScope($tenantId);
    }

    /**
     * LFR-DASH-001 - the pipeline state list.
     *
     * @return list<string>
     */
    public function states(): array
    {
        return self::LEAD_STATES;
    }

    /**
     * Per-state lead counts for the signed-in tenant (FR-DASH-001).
     *
     * Returns a map keyed by every LEAD_STATE (zeros included) so the view can
     * render a stable column order even when a state has no leads. The tenant
     * predicate is generated by TenantScope and the value bound internally.
     *
     * @return array<string, int>
     */
    public function leadStatusCounts(): array
    {
        $counts = [];
        foreach (self::LEAD_STATES as $state) {
            $counts[$state] = 0;
        }

        $scope = new TenantScope($this->tenantId);
        $statement = $this->pdo->prepare(
            'SELECT status, COUNT(*) AS c FROM leads'
            . $scope->where('status IN (:s0, :s1, :s2, :s3, :s4)')
            . ' GROUP BY status'
        );
        $scope->bindTo($statement);
        $statement->bindValue('s0', self::LEAD_STATES[0]);
        $statement->bindValue('s1', self::LEAD_STATES[1]);
        $statement->bindValue('s2', self::LEAD_STATES[2]);
        $statement->bindValue('s3', self::LEAD_STATES[3]);
        $statement->bindValue('s4', self::LEAD_STATES[4]);
        $statement->execute();

        $rows = $statement->fetchAll(PDO::FETCH_ASSOC);

        foreach ($rows as $row) {
            if (!is_array($row) || !isset($row['status'], $row['c'])) {
                throw new UnexpectedValueException('Unexpected row from lead status aggregate.');
            }
            $status = is_string($row['status']) ? $row['status'] : '';
            $count = is_numeric($row['c']) ? (int) $row['c'] : 0;
            if (array_key_exists($status, $counts)) {
                $counts[$status] = $count;
            }
        }

        return $counts;
    }

    /**
     * LBR-5.8 - the "awaiting human" exceptions queue.
     *
     * Lead AI analyses still in 'pending' status are the human-decision backlog:
     * a lead whose analysis has not completed (or failed closed) is held for a
     * person, never auto-actioned. Tenant-scoped.
     *
     * @return list<array<string, mixed>>
     */
    public function awaitingHuman(): array
    {
        $scope = new TenantScope($this->tenantId);
        $statement = $this->pdo->prepare(
            'SELECT id, lead_id, status FROM lead_ai_analyses' . $scope->where('status = :st')
        );
        $scope->bindTo($statement);
        $statement->bindValue('st', 'pending');
        $statement->execute();

        return $this->rows($statement);
    }

    /**
     * LBR-5.8 - the "failed deliveries" exceptions queue.
     *
     * message_deliveries gained a nullable status + error column in migration
     * 009 so a failed delivery is real data, not invented. Tenant-scoped.
     *
     * @return list<array<string, mixed>>
     */
    public function failedDeliveries(): array
    {
        $scope = new TenantScope($this->tenantId);
        $statement = $this->pdo->prepare(
            'SELECT id, lead_id, channel, recipient, status, error'
            . ' FROM message_deliveries' . $scope->where('status = :st')
        );
        $scope->bindTo($statement);
        $statement->bindValue('st', 'failed');
        $statement->execute();

        return $this->rows($statement);
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function rows(PDOStatement $statement): array
    {
        $fetched = $statement->fetchAll(PDO::FETCH_ASSOC);

        $rows = [];
        foreach ($fetched as $row) {
            if (!is_array($row)) {
                throw new UnexpectedValueException('Unexpected non-array row from dashboard query.');
            }
            $rows[] = $row;
        }

        return $rows;
    }
}
