<?php

declare(strict_types=1);

namespace App\Leads;

use App\Security\RateLimiter;
use App\Tenancy\TenantScope;
use Closure;
use DateTimeImmutable;
use DomainException;
use PDO;
use PDOStatement;
use RuntimeException;
use Throwable;

/**
 * Public lead capture: validate, throttle, PERSIST, then analyse.
 *
 * ORDER IS THE WHOLE DESIGN. This endpoint is public and unauthenticated, so
 * the sequence below is what stands in for a session:
 *
 *   1. THROTTLE FIRST, FAIL CLOSED (LFR-CAP-003). The counter lives in Redis
 *      via App\Security\RateLimiter, so discarding a cookie does not reset it.
 *      If Redis is unreachable the request is REFUSED, not waved through -
 *      degrading to unlimited submissions when the limiter breaks is the exact
 *      bypass the shared counter exists to close. Throttling before validation
 *      also means a flood of malformed posts costs no database work.
 *
 *   2. HONEYPOT, ACCEPT BUT DO NOT PERSIST (LFR-CAP-001). A filled decoy field
 *      returns the SAME 202 receipt a real capture gets, with a correlation id
 *      that leads nowhere. A 422 or a silent 200 would both tell the bot it was
 *      detected - and telling it is what gets the decoy renamed.
 *
 *   3. VALIDATE (LFR-CAP-002). Invalid input yields 422 and ZERO records: the
 *      transaction below is never opened, so there is nothing to clean up.
 *
 *   4. PERSIST AND COMMIT (LFR-CAP-004), lead and raw submission together in
 *      one transaction.
 *
 *   5. ONLY THEN ANALYSE (LBR-5.1). The analyzer is injected and may be a stub,
 *      absent, or a real queue publisher later - this class never calls a
 *      model. Whatever it is, it runs AFTER the commit, and its failure is
 *      caught and recorded: the lead stays on disk and moves to 'Review'. A
 *      lead lost because a model timed out is a lead the business never knew
 *      it had.
 *
 * WHY NOT A TenantRepository SUBCLASS: capture writes THREE tables inside one
 * unit of work and needs the generated lead id to chain them, which is a
 * service concern rather than a per-table repository one. Tenancy is not
 * weakened by that: every statement here is built from TenantScope::COLUMN and
 * TenantScope::PARAM and bound by TenantScope::bindTo(), so the predicate is
 * generated by the same class the repositories use and cannot be omitted or
 * misspelled at a call site (FR-TEN-002 / AC-001). Nothing here uses PDO::query
 * or PDO::exec - build/phpstan/NoUnscopedClientQueryRule.php enforces that.
 *
 * © AI WebScapes 2026
 */
final class LeadService
{
    /** A freshly captured lead, awaiting analysis. */
    public const STATUS_NEW = 'New';

    /** LBR-5.1: analysis failed, a human must look at it. */
    public const STATUS_REVIEW = 'Review';

    /**
     * LFR-AI-003. Below this the model's own verdict is not acted on: the lead
     * goes to a human instead. The threshold lives here rather than at the call
     * site so "how sure is sure enough" is one decision, not per-caller taste.
     */
    public const MIN_CONFIDENCE = 0.5;

    /** Used when neither a business rule nor the model names a usable owner. */
    public const OWNER_UNASSIGNED = 'unassigned';

    public const RESULT_ACCEPTED = 202;

    public const RESULT_INVALID = 422;

    public const RESULT_THROTTLED = 429;

    /**
     * The decoy field. Named `website` because that is what the baseline form
     * in legacy/api/demo-request.php already uses, so existing bot tooling
     * keeps filling it.
     */
    private const HONEYPOT_FIELD = 'website';

    /**
     * One receipt, four outcomes. Deliberately identical for a real capture and
     * a honeypot hit, and deliberately free of any record identifier - the
     * correlation id is a support handle, not a row id (Lead FRD Table 3).
     */
    private const RECEIPT = 'Request received. Our team will review it and follow up.';

    private const MAX_NAME = 120;

    private const MAX_EMAIL = 190;

    private const MAX_COMPANY = 160;

    private const MAX_NEED = 2000;

    /**
     * How far back detectDuplicate() looks. A window rather than "for ever":
     * the same person enquiring again eighteen months later is a new
     * opportunity, not a duplicate, and linking it as one buries it under a
     * closed record.
     */
    private const DUPLICATE_WINDOW_DAYS = 30;

    /**
     * LFR-AI-002. The ONLY lead fields that may reach the model. An allow-list:
     * a field added to the intake form tomorrow is absent from the AI request
     * until someone deliberately adds it here.
     *
     * Note what is missing - name, email, phone, ip_hash. The model classifies
     * an enquiry; it does not need to know who sent it, and identifiers handed
     * to a third party cannot be recalled.
     */
    private const AI_ALLOWED_FIELDS = ['company', 'automation_need', 'source'];

    /**
     * @param Closure(int, array<string, string|null>): array<string, mixed>|null $analyzer
     *        Injected on purpose: in tests it is a stub that throws, in
     *        production it will hand off to the AI pipeline. Null means
     *        "queued, nothing consuming it yet", which leaves the analysis row
     *        at 'pending'.
     */
    public function __construct(
        private PDO $pdo,
        private RateLimiter $rateLimiter,
        private ?Closure $analyzer = null
    ) {
    }

    /**
     * @param  array<string, mixed> $input Normalised request fields, plus the
     *                                     `ip_hash` the controller derived.
     * @return array{status: int, correlation_id: string, message: string, errors: array<string, string>}
     */
    public function capture(array $input, string $tenantId): array
    {
        $scope = new TenantScope($this->tenantNumber($tenantId));
        $correlationId = bin2hex(random_bytes(16));

        if (!$this->withinRateLimit($this->throttleKey($input))) {
            return $this->receipt(self::RESULT_THROTTLED, $correlationId, 'Too many requests. Try again later.');
        }

        if ($this->honeypotFilled($input)) {
            // Accepted, and nothing written. Same shape as success on purpose.
            return $this->receipt(self::RESULT_ACCEPTED, $correlationId);
        }

        $errors = $this->validate($input);
        if ($errors !== []) {
            return $this->receipt(
                self::RESULT_INVALID,
                $correlationId,
                'Please correct the highlighted fields.',
                $errors
            );
        }

        // Read-only, and BEFORE the insert: run afterwards it would match the
        // row it is about to create. LFR-DUP-001 links, never merges - the
        // earlier lead is left exactly as the earlier visitor sent it.
        $duplicateOf = $this->findDuplicate($scope, $input);

        $leadId = $this->persist($scope, $input, $correlationId);

        // Past this line the lead is durable. Everything below may fail without
        // costing the business the enquiry (LBR-5.1).
        $this->recordInteraction($scope, $leadId, $input);

        if ($duplicateOf !== null) {
            $this->linkDuplicate($scope, $duplicateOf, $leadId);
        }

        $this->queueAnalysis($scope, $leadId, $input);

        return $this->receipt(self::RESULT_ACCEPTED, $correlationId);
    }

    /**
     * Writes the lead, its raw submission and its opening status-history row as
     * one unit, then commits.
     *
     * JOINING AN OUTER TRANSACTION: PDO/MySQL has no nested transactions, and
     * the test harness wraps every test in one. When a transaction is already
     * open this method takes part in it instead of calling beginTransaction()
     * and throwing - the atomicity guarantee is then the OUTER transaction's,
     * which is strictly no weaker. Only the owner commits or rolls back.
     *
     * @param  array<string, mixed> $input
     * @return int The generated lead id.
     */
    private function persist(TenantScope $scope, array $input, string $correlationId): int
    {
        $owns = !$this->pdo->inTransaction();
        if ($owns) {
            $this->pdo->beginTransaction();
        }

        try {
            $this->execute(
                'INSERT INTO leads (' . TenantScope::COLUMN . ', correlation_id, email, name, company,'
                . ' source, status, ip_hash)'
                . ' VALUES (:' . TenantScope::PARAM . ', :correlation_id, :email, :name, :company,'
                . ' :source, :status, :ip_hash)',
                $scope,
                [
                    'correlation_id' => $correlationId,
                    'email' => $this->text($input, 'email', self::MAX_EMAIL),
                    'name' => $this->text($input, 'name', self::MAX_NAME),
                    'company' => $this->nullableText($input, 'company', self::MAX_COMPANY),
                    'source' => $this->text($input, 'source', 64) !== ''
                        ? $this->text($input, 'source', 64)
                        : 'public_form',
                    'status' => self::STATUS_NEW,
                    'ip_hash' => $this->nullableText($input, 'ip_hash', 64),
                ]
            );

            $leadId = $this->lastInsertId();

            $this->execute(
                'INSERT INTO lead_submissions (' . TenantScope::COLUMN . ', lead_id, payload_json, ip_hash,'
                . ' user_agent)'
                . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :payload_json, :ip_hash, :user_agent)',
                $scope,
                [
                    'lead_id' => $leadId,
                    'payload_json' => $this->encode($this->submissionPayload($input)),
                    'ip_hash' => $this->nullableText($input, 'ip_hash', 64),
                    'user_agent' => $this->nullableText($input, 'user_agent', 255),
                ]
            );

            $this->recordStatus($scope, $leadId, null, self::STATUS_NEW, 'captured');

            if ($owns) {
                $this->pdo->commit();
            }

            return $leadId;
        } catch (Throwable $failure) {
            if ($owns && $this->pdo->inTransaction()) {
                $this->pdo->rollBack();
            }

            throw $failure;
        }
    }

    /**
     * Records the analysis as 'pending' and then hands the lead to the injected
     * analyzer, if there is one.
     *
     * The pending row is written FIRST and committed with nothing depending on
     * the analyzer, so an analyzer that dies mid-call - or a process killed
     * outright - still leaves a visible queue entry rather than a lead nobody
     * knows is waiting.
     *
     * @param array<string, mixed> $input
     */
    private function queueAnalysis(TenantScope $scope, int $leadId, array $input): void
    {
        $this->execute(
            'INSERT INTO lead_ai_analyses (' . TenantScope::COLUMN . ', lead_id, status)'
            . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :status)',
            $scope,
            ['lead_id' => $leadId, 'status' => 'pending']
        );

        $analysisId = $this->lastInsertId();

        if ($this->analyzer === null) {
            return;
        }

        try {
            $analysis = ($this->analyzer)($leadId, $this->analyzerView($input));

            $this->updateScoped(
                'lead_ai_analyses',
                ['status' => 'complete', 'analysis_json' => $this->encode($analysis)],
                $scope,
                $analysisId
            );
        } catch (Throwable $failure) {
            // LBR-5.1. The lead is already committed - the only thing left to
            // decide is who looks at it, and the answer is a human.
            $this->updateScoped(
                'lead_ai_analyses',
                [
                    'status' => 'failed',
                    'error_message' => mb_substr($failure->getMessage(), 0, 255),
                ],
                $scope,
                $analysisId
            );

            $this->updateScoped('leads', ['status' => self::STATUS_REVIEW], $scope, $leadId);
            $this->recordStatus($scope, $leadId, self::STATUS_NEW, self::STATUS_REVIEW, 'ai_analysis_failed');
        }
    }

    /**
     * @param array<string, scalar|null> $values
     */
    private function updateScoped(string $table, array $values, TenantScope $scope, int $id): void
    {
        $assignments = [];
        $params = ['row_id' => $id];

        foreach ($values as $column => $value) {
            // FR-TEN-001: the scope column is never writable, not even here
            // where every column name is a local constant.
            $scope->rejectTenantColumnWrite($column);

            $assignments[] = $column . ' = :' . $column;
            $params[$column] = $value;
        }

        $this->execute(
            'UPDATE ' . $this->identifier($table) . ' SET ' . implode(', ', $assignments)
            . $scope->where('id = :row_id'),
            $scope,
            $params
        );
    }

    private function recordStatus(
        TenantScope $scope,
        int $leadId,
        ?string $from,
        string $to,
        string $reason
    ): void {
        $this->execute(
            'INSERT INTO lead_status_history (' . TenantScope::COLUMN . ', lead_id, from_status, to_status, reason)'
            . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :from_status, :to_status, :reason)',
            $scope,
            [
                'lead_id' => $leadId,
                'from_status' => $from,
                'to_status' => $to,
                'reason' => $reason,
            ]
        );
    }

    /**
     * The single choke point: prepare, bind the caller's parameters, then let
     * TenantScope bind the tenant LAST and unconditionally.
     *
     * @param array<string, scalar|null> $params
     */
    private function execute(string $sql, TenantScope $scope, array $params): PDOStatement
    {
        $scope->rejectCallerBinding($params);

        $statement = $this->pdo->prepare($sql);
        if ($statement === false) {
            // Unreachable under ERRMODE_EXCEPTION, kept so a laxer PDO
            // configuration cannot turn a failed prepare into a silent no-op.
            throw new RuntimeException(sprintf('Failed to prepare statement: %s', $sql));
        }

        foreach ($params as $name => $value) {
            $statement->bindValue(':' . $name, $value, $this->pdoType($value));
        }

        $scope->bindTo($statement);
        $statement->execute();

        return $statement;
    }

    private function pdoType(bool|float|int|string|null $value): int
    {
        return match (true) {
            $value === null => PDO::PARAM_NULL,
            is_bool($value) => PDO::PARAM_BOOL,
            is_int($value) => PDO::PARAM_INT,
            default => PDO::PARAM_STR,
        };
    }

    private function lastInsertId(): int
    {
        $id = $this->pdo->lastInsertId();
        if ($id === false || !ctype_digit($id)) {
            // Surfaced rather than coerced to 0, which would hand the caller a
            // plausible-looking id pointing at nothing.
            throw new RuntimeException('The driver reported no generated key for the inserted lead row.');
        }

        return (int) $id;
    }

    /**
     * LFR-CAP-003, fail closed. A limiter that cannot be reached is treated as
     * a limiter that said no.
     */
    private function withinRateLimit(string $key): bool
    {
        try {
            return $this->rateLimiter->hit($key);
        } catch (Throwable $unreachable) {
            error_log('Lead capture rate limiter unavailable: ' . $unreachable->getMessage());

            return false;
        }
    }

    /**
     * The throttle identity. The controller supplies the HMAC of the client IP.
     * When it is absent every such request shares ONE bucket rather than each
     * getting its own - unattributable traffic is throttled collectively
     * instead of being handed an unlimited allowance.
     *
     * @param array<string, mixed> $input
     */
    private function throttleKey(array $input): string
    {
        $key = $this->text($input, 'ip_hash', 64);

        return $key !== '' ? $key : 'unattributed';
    }

    /**
     * @param array<string, mixed> $input
     */
    private function honeypotFilled(array $input): bool
    {
        return $this->text($input, self::HONEYPOT_FIELD, 255) !== '';
    }

    /**
     * @param  array<string, mixed> $input
     * @return array<string, string>
     */
    private function validate(array $input): array
    {
        $errors = [];

        if ($this->text($input, 'name', self::MAX_NAME) === '') {
            $errors['name'] = 'Name is required.';
        }

        $email = $this->text($input, 'email', self::MAX_EMAIL);
        if ($email === '' || filter_var($email, FILTER_VALIDATE_EMAIL) === false) {
            $errors['email'] = 'A valid email is required.';
        }

        if ($this->text($input, 'automation_need', self::MAX_NEED) === '') {
            $errors['automation_need'] = 'Workflow details are required.';
        }

        return $errors;
    }

    /**
     * The verbatim submission, minus the honeypot (which is noise) and minus
     * the derived ip_hash (which has its own column).
     *
     * @param  array<string, mixed> $input
     * @return array<string, string>
     */
    private function submissionPayload(array $input): array
    {
        $payload = [];

        foreach ($input as $field => $value) {
            if ($field === self::HONEYPOT_FIELD || $field === 'ip_hash') {
                continue;
            }

            if (is_scalar($value)) {
                $payload[$field] = mb_substr((string) $value, 0, self::MAX_NEED);
            }
        }

        return $payload;
    }

    /**
     * What the analyzer is allowed to see. A narrow, typed view rather than the
     * raw request array: the AI stage is the least trusted consumer here, so it
     * gets the parsed fields and nothing else.
     *
     * @param  array<string, mixed> $input
     * @return array<string, string|null>
     */
    private function analyzerView(array $input): array
    {
        return [
            'name' => $this->text($input, 'name', self::MAX_NAME),
            'email' => $this->text($input, 'email', self::MAX_EMAIL),
            'company' => $this->nullableText($input, 'company', self::MAX_COMPANY),
            'automation_need' => $this->text($input, 'automation_need', self::MAX_NEED),
        ];
    }

    /**
     * @param array<string, mixed> $values
     */
    private function encode(array $values): string
    {
        $json = json_encode($values, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        // json_encode returns false on malformed UTF-8 - storing "false" as a
        // JSON column value would fail at the database anyway, so say why here.
        return $json === false ? '{}' : $json;
    }

    /**
     * @param array<string, mixed> $input
     */
    private function text(array $input, string $field, int $maxLength): string
    {
        $value = $input[$field] ?? '';
        if (!is_scalar($value)) {
            return '';
        }

        return mb_substr(trim((string) $value), 0, $maxLength);
    }

    /**
     * @param array<string, mixed> $input
     */
    private function nullableText(array $input, string $field, int $maxLength): ?string
    {
        $value = $this->text($input, $field, $maxLength);

        return $value !== '' ? $value : null;
    }

    /**
     * The tenant arrives as a string from the transport layer. Anything that is
     * not a positive integer is refused HERE rather than being cast to 0 and
     * handed to TenantScope as "tenant zero".
     */
    private function tenantNumber(string $tenantId): ?int
    {
        $trimmed = trim($tenantId);

        return ctype_digit($trimmed) ? (int) $trimmed : null;
    }

    /**
     * Table names cannot be bound, so the two constants this class interpolates
     * are still checked - a repository has no reason to name a table with a
     * backtick or a semicolon in it.
     */
    private function identifier(string $name): string
    {
        if (preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $name) !== 1) {
            throw new RuntimeException(sprintf('Refusing to interpolate "%s" as a table name.', $name));
        }

        return $name;
    }

    /**
     * @param  array<string, string> $errors
     * @return array{status: int, correlation_id: string, message: string, errors: array<string, string>}
     */
    private function receipt(
        int $status,
        string $correlationId,
        string $message = self::RECEIPT,
        array $errors = []
    ): array {
        return [
            'status' => $status,
            'correlation_id' => $correlationId,
            'message' => $message,
            'errors' => $errors,
        ];
    }

    // ---------------------------------------------------------------------
    // P1-T11: duplicates, AI analysis, deterministic routing.
    // All helpers below are tenant-scoped through TenantScope, exactly like
    // the capture path above. Nothing here uses PDO::query/exec directly.
    // ---------------------------------------------------------------------

    /**
     * LFR-DUP-001. Returns the id of an earlier lead in the SAME tenant that
     * looks like a repeat of this one, or null. Read-only and called BEFORE
     * the insert so it can never match the row it is about to create; the
     * earlier lead is left exactly as sent.
     *
     * @param array<string, mixed> $input
     */
    private function findDuplicate(TenantScope $scope, array $input): ?int
    {
        $email = $this->normalizeEmail($this->text($input, 'email', self::MAX_EMAIL));
        if ($email === '') {
            return null;
        }

        $since = (new DateTimeImmutable())->modify('-' . self::DUPLICATE_WINDOW_DAYS . ' days');

        $statement = $this->execute(
            'SELECT id FROM leads ' . $scope->where('email = :email AND created_at >= :since'),
            $scope,
            ['email' => $email, 'since' => $since->format('Y-m-d H:i:s')]
        );

        $hit = $statement->fetchColumn();
        if (is_numeric($hit)) {
            return (int) $hit;
        }

        return null;
    }

    /**
     * Records that we heard from a lead again. Every submission is its own
     * interaction row, so a repeat enquiry ACCUMULATES evidence rather than
     * overwriting it.
     *
     * @param array<string, mixed> $input
     */
    private function recordInteraction(TenantScope $scope, int $leadId, array $input): void
    {
        $this->execute(
            'INSERT INTO lead_interactions (' . TenantScope::COLUMN . ', lead_id, channel, direction, body)'
            . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :channel, :direction, :body)',
            $scope,
            [
                'lead_id' => $leadId,
                'channel' => 'note',
                'direction' => 'inbound',
                'body' => $this->nullableText($input, 'automation_need', self::MAX_NEED),
            ]
        );
    }

    /**
     * LFR-DUP-001. Links a repeat submission to the original it resembles.
     * INSERT IGNORE honours the unique (tenant, lead, duplicate) pair, so a
     * second pass over the same pair is a no-op rather than a duplicate-key
     * error. The original lead row is NEVER updated by this.
     */
    private function linkDuplicate(TenantScope $scope, int $originalId, int $duplicateId): void
    {
        $this->execute(
            'INSERT IGNORE INTO lead_duplicates (' . TenantScope::COLUMN . ', lead_id, duplicate_lead_id)'
            . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :duplicate_lead_id)',
            $scope,
            ['lead_id' => $originalId, 'duplicate_lead_id' => $duplicateId]
        );
    }

    /**
     * LFR-AI-001 + LFR-AI-003. Turns an (untrusted, arbitrarily-shaped) model
     * verdict into a typed AnalysisResult and APPENDS a new analysis version
     * for the lead - never an UPDATE of the prior verdict.
     *
     * If the model's confidence is below the floor, the system keeps the lead
     * for a human (status 'Review') instead of acting on an unsure verdict.
     *
     * @param array<string, mixed> $aiResult
     */
    public function analyze(array $aiResult, string $tenantId, ?int $leadId = null): AnalysisResult
    {
        $scope = new TenantScope($this->tenantNumber($tenantId));

        $confidence = is_numeric($aiResult['confidence'] ?? null) ? (float) $aiResult['confidence'] : 0.0;
        $status = $this->aiStatus($confidence);

        $result = new AnalysisResult(
            summary: $this->stringField($aiResult, 'summary'),
            intent: $this->stringField($aiResult, 'intent'),
            category: $this->stringField($aiResult, 'category'),
            urgency: $this->stringField($aiResult, 'urgency'),
            nextStep: $this->stringField($aiResult, 'next_step'),
            riskFlags: is_array($aiResult['risk_flags'] ?? null)
                ? array_values(array_map('strval', $aiResult['risk_flags']))
                : [],
            confidence: $confidence,
            rationale: $this->stringField($aiResult, 'rationale'),
            status: $status
        );

        // Persist the verdict as a NEW row, but only when it has a lead to
        // attach to. A lead-less call (e.g. a pure unit check of the
        // verdict->status mapping) still returns a fully-formed AnalysisResult;
        // it simply has nowhere to be filed. Re-analysis of a real lead grows
        // the history - it never rewrites the prior verdict.
        if ($leadId !== null) {
            // The pipeline `status` enum (pending/complete/failed) records that
            // a verdict was produced; the human DECISION (New vs Review) is the
            // system's call and is filed inside the JSON, since it is not part
            // of the model's own schema. AnalysisResult deliberately keeps the
            // two apart.
            $this->execute(
                'INSERT INTO lead_ai_analyses (' . TenantScope::COLUMN . ', lead_id, status, analysis_json)'
                . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :status, :analysis_json)',
                $scope,
                [
                    'lead_id' => $leadId,
                    'status' => 'complete',
                    'analysis_json' => $this->encode(array_merge(
                        $result->toArray(),
                        [
                            'version' => $this->nextAnalysisVersion($scope, $leadId),
                            'decision' => $status,
                        ]
                    )),
                ]
            );
        }

        return $result;
    }

    /**
     * LFR-ROUTE-001. The business rule decides; the model only suggests. A
     * parsed rule (e.g. "owner=always-sales") wins outright, and the decision
     * records that a human-authored rule - not the model - made the call.
     *
     * @param array<string, mixed> $aiSuggestion
     */
    public function route(array $aiSuggestion, string $businessRule): RouteDecision
    {
        $ruleOwner = $this->parseRuleOwner($businessRule);
        if ($ruleOwner !== null) {
            return new RouteDecision($ruleOwner, RouteDecision::SOURCE_RULE);
        }

        $aiOwner = is_string($aiSuggestion['owner'] ?? null) ? $aiSuggestion['owner'] : '';
        if ($aiOwner !== '') {
            return new RouteDecision($aiOwner, RouteDecision::SOURCE_AI);
        }

        return new RouteDecision(self::OWNER_UNASSIGNED, RouteDecision::SOURCE_DEFAULT);
    }

    /**
     * LFR-PRIV-001. Returns a portable snapshot of a lead and its cascade data
     * (data-subject access / portability). Read-only and tenant-scoped; it
     * copies the personal-data rows into an array WITHOUT deleting them. The
     * companion deleteLead() is what erases them, and the erasure is itself
     * recorded in the audit log (which is NOT a child of leads) so the trail
     * survives after the data is gone.
     *
     * @return array<string, mixed>|null Null if no such lead exists in scope.
     */
    public function exportLead(int $leadId, string $tenantId): ?array
    {
        $scope = new TenantScope($this->tenantNumber($tenantId));

        $statement = $this->execute(
            'SELECT * FROM leads ' . $scope->where('id = :id'),
            $scope,
            ['id' => $leadId]
        );

        $lead = $statement->fetch(\PDO::FETCH_ASSOC);
        if (!is_array($lead)) {
            return null;
        }

        return [
            'lead' => $lead,
            'submissions' => $this->exportChildren(
                $scope,
                $leadId,
                'SELECT * FROM lead_submissions ' . $scope->where('lead_id = :lead_id')
            ),
            'analyses' => $this->exportChildren(
                $scope,
                $leadId,
                'SELECT * FROM lead_ai_analyses ' . $scope->where('lead_id = :lead_id')
            ),
            'interactions' => $this->exportChildren(
                $scope,
                $leadId,
                'SELECT * FROM lead_interactions ' . $scope->where('lead_id = :lead_id')
            ),
            'tasks' => $this->exportChildren(
                $scope,
                $leadId,
                'SELECT * FROM lead_tasks ' . $scope->where('lead_id = :lead_id')
            ),
            'corrections' => $this->exportChildren(
                $scope,
                $leadId,
                'SELECT * FROM lead_field_corrections ' . $scope->where('lead_id = :lead_id')
            ),
            'duplicates' => $this->exportChildren(
                $scope,
                $leadId,
                'SELECT * FROM lead_duplicates ' . $scope->where('lead_id = :lead_id')
            ),
        ];
    }

    /**
     * LFR-PRIV-001 + LFR-SEC-001. Erases a lead and its cascade children, then
     * records the erasure in the audit log.
     *
     * LFR-SEC-001 is enforced structurally: the DELETE is built from
     * TenantScope::where('id = :id'), so a call scoped to a DIFFERENT tenant
     * than the lead's own tenant resolves to NO row - the lead cannot be
     * deleted cross-tenant. We fail CLOSED and LOUD: if the scoped delete
     * reports zero rows, we throw a 403 rather than "succeeding" silently,
     * because a real deletion always removes at least the lead row. The audit
     * row is written only when an actual deletion occurred.
     *
     * @throws DomainException With code 403 when the lead is not in the
     *                         caller's scope (LFR-SEC-001).
     */
    public function deleteLead(int $leadId, string $tenantId): void
    {
        $scope = new TenantScope($this->tenantNumber($tenantId));

        // The lead is the parent; its children cascade via ON DELETE CASCADE.
        // Wrapped in the surrounding transaction so the audit write and the
        // delete commit together (or roll back together).
        $affected = $this->execute(
            'DELETE FROM leads ' . $scope->where('id = :id'),
            $scope,
            ['id' => $leadId]
        )->rowCount();

        if ($affected === 0) {
            // Nothing was in scope to delete. Throwing - not returning - is the
            // secure choice: a caller asking to delete another tenant's lead
            // must be told no, and must never be able to read "success".
            throw new DomainException('Not authorised to delete this lead.', 403);
        }

        // The erasure is retained independently of the lead. audit_log is NOT a
        // child of leads, so this row outlives the cascade delete (LFR-PRIV-001).
        $this->execute(
            'INSERT INTO audit_log (' . TenantScope::COLUMN . ', actor_user_id, event, outcome, object_type, object_id, detail)'
            . ' VALUES (:' . TenantScope::PARAM . ', :actor, :event, :outcome, :object_type, :object_id, :detail)',
            $scope,
            [
                'actor' => null,
                'event' => 'lead.erasure',
                'outcome' => 'success',
                'object_type' => 'lead',
                'object_id' => (string) $leadId,
                'detail' => 'lead and cascade data erased',
            ]
        );
    }

    /**
     * Runs a child-table export query and returns every row as a list.
     *
     * @return list<array<string, mixed>>
     */
    private function exportChildren(TenantScope $scope, int $leadId, string $sql): array
    {
        $statement = $this->execute($sql, $scope, ['lead_id' => $leadId]);

        /** @var list<array<string, mixed>> $rows */
        $rows = $statement->fetchAll(\PDO::FETCH_ASSOC);

        return $rows;
    }

    /**
     * LFR-AI-002. Builds the redacted payload for the model. Allow-list only:
     * the payload is assembled from AI_ALLOWED_FIELDS, so a field the intake
     * form grows tomorrow is absent until deliberately added here - the
     * failure mode of "forgot to list it" is omission, never a PII leak.
     *
     * @param array<string, mixed> $lead
     */
    public function buildAIRequest(array $lead): AIRequest
    {
        $allowed = [];
        foreach (self::AI_ALLOWED_FIELDS as $field) {
            $value = $lead[$field] ?? null;
            if (is_scalar($value) && $value !== '') {
                $allowed[$field] = (string) $value;
            }
        }

        return new AIRequest($allowed);
    }

    /**
     * The next version number for a lead's analysis history. 1-based; a fresh
     * lead starts at version 1 and every re-analysis appends.
     */
    private function nextAnalysisVersion(TenantScope $scope, ?int $leadId): int
    {
        if ($leadId === null) {
            return 1;
        }

        // Count only completed verdicts this method produced. capture() also
        // seeds a 'pending' placeholder row (see queueAnalysis), which must
        // not offset the re-analysis version numbering - a re-analysis of a
        // lead is version 1, 2, ... of the verdicts, not of the queue markers.
        $statement = $this->execute(
            'SELECT COUNT(*) FROM lead_ai_analyses ' . $scope->where('lead_id = :lead_id AND status = :status'),
            $scope,
            ['lead_id' => $leadId, 'status' => 'complete']
        );

        $count = $statement->fetchColumn();

        return is_numeric($count) ? (int) $count + 1 : 1;
    }

    /**
     * LFR-AI-003. Below the confidence floor the verdict is not acted on: a
     * human reviews it.
     */
    private function aiStatus(float $confidence): string
    {
        return $confidence < self::MIN_CONFIDENCE ? self::STATUS_REVIEW : self::STATUS_NEW;
    }

    /**
     * Parses "owner=always-<team>" into "<team>". The "always-" prefix is the
     * signal that the rule is deterministic, not a suggestion. Returns null if
     * the rule does not name an owner we recognise.
     */
    private function parseRuleOwner(string $rule): ?string
    {
        if (preg_match('/^\s*owner\s*=\s*always-([a-z0-9_-]+)\s*$/i', $rule, $matches) !== 1) {
            return null;
        }

        // $matches[1] is non-empty (the pattern requires at least one char),
        // so the normalised team is always non-empty.
        return strtolower($matches[1]);
    }

    /**
     * Normalises an email for duplicate comparison: lowercased and trimmed.
     * Comparison is on the stored, normalised form so "A@X.COM" and "a@x.com"
     * collide as the same person.
     */
    private function normalizeEmail(string $email): string
    {
        return strtolower(trim($email));
    }

    /**
     * @param array<string, mixed> $data
     */
    private function stringField(array $data, string $key): string
    {
        $value = $data[$key] ?? null;

        return is_scalar($value) ? (string) $value : '';
    }
}
