<?php

declare(strict_types=1);

namespace App\Leads;

use App\Security\RateLimiter;
use App\Tenancy\TenantScope;
use Closure;
use PDO;
use PDOStatement;
use RuntimeException;
use Throwable;

/**
 * Public lead capture: validate, throttle, PERSIST, then analyse.
 *
 * ORDER IS THE WHOLE DESIGN. This endpoint is public and unauthenticated, so
 * the sequence below is what stands in for a session:
 *
 *   1. THROTTLE FIRST, FAIL CLOSED (LFR-CAP-003). The counter lives in Redis
 *      via App\Security\RateLimiter, so discarding a cookie does not reset it.
 *      If Redis is unreachable the request is REFUSED, not waved through -
 *      degrading to unlimited submissions when the limiter breaks is the exact
 *      bypass the shared counter exists to close. Throttling before validation
 *      also means a flood of malformed posts costs no database work.
 *
 *   2. HONEYPOT, ACCEPT BUT DO NOT PERSIST (LFR-CAP-001). A filled decoy field
 *      returns the SAME 202 receipt a real capture gets, with a correlation id
 *      that leads nowhere. A 422 or a silent 200 would both tell the bot it was
 *      detected - and telling it is what gets the decoy renamed.
 *
 *   3. VALIDATE (LFR-CAP-002). Invalid input yields 422 and ZERO records: the
 *      transaction below is never opened, so there is nothing to clean up.
 *
 *   4. PERSIST AND COMMIT (LFR-CAP-004), lead and raw submission together in
 *      one transaction.
 *
 *   5. ONLY THEN ANALYSE (LBR-5.1). The analyzer is injected and may be a stub,
 *      absent, or a real queue publisher later - this class never calls a
 *      model. Whatever it is, it runs AFTER the commit, and its failure is
 *      caught and recorded: the lead stays on disk and moves to 'Review'. A
 *      lead lost because a model timed out is a lead the business never knew
 *      it had.
 *
 * WHY NOT A TenantRepository SUBCLASS: capture writes THREE tables inside one
 * unit of work and needs the generated lead id to chain them, which is a
 * service concern rather than a per-table repository one. Tenancy is not
 * weakened by that: every statement here is built from TenantScope::COLUMN and
 * TenantScope::PARAM and bound by TenantScope::bindTo(), so the predicate is
 * generated by the same class the repositories use and cannot be omitted or
 * misspelled at a call site (FR-TEN-002 / AC-001). Nothing here uses PDO::query
 * or PDO::exec - build/phpstan/NoUnscopedClientQueryRule.php enforces that.
 *
 * © AI WebScapes 2026
 */
final class LeadService
{
    /** A freshly captured lead, awaiting analysis. */
    public const STATUS_NEW = 'New';

    /** LBR-5.1: analysis failed, a human must look at it. */
    public const STATUS_REVIEW = 'Review';

    public const RESULT_ACCEPTED = 202;

    public const RESULT_INVALID = 422;

    public const RESULT_THROTTLED = 429;

    /**
     * The decoy field. Named `website` because that is what the baseline form
     * in legacy/api/demo-request.php already uses, so existing bot tooling
     * keeps filling it.
     */
    private const HONEYPOT_FIELD = 'website';

    /**
     * One receipt, four outcomes. Deliberately identical for a real capture and
     * a honeypot hit, and deliberately free of any record identifier - the
     * correlation id is a support handle, not a row id (Lead FRD Table 3).
     */
    private const RECEIPT = 'Request received. Our team will review it and follow up.';

    private const MAX_NAME = 120;

    private const MAX_EMAIL = 190;

    private const MAX_COMPANY = 160;

    private const MAX_NEED = 2000;

    /**
     * @param Closure(int, array<string, string|null>): array<string, mixed>|null $analyzer
     *        Injected on purpose: in tests it is a stub that throws, in
     *        production it will hand off to the AI pipeline. Null means
     *        "queued, nothing consuming it yet", which leaves the analysis row
     *        at 'pending'.
     */
    public function __construct(
        private PDO $pdo,
        private RateLimiter $rateLimiter,
        private ?Closure $analyzer = null
    ) {
    }

    /**
     * @param  array<string, mixed> $input Normalised request fields, plus the
     *                                     `ip_hash` the controller derived.
     * @return array{status: int, correlation_id: string, message: string, errors: array<string, string>}
     */
    public function capture(array $input, string $tenantId): array
    {
        $scope = new TenantScope($this->tenantNumber($tenantId));
        $correlationId = bin2hex(random_bytes(16));

        if (!$this->withinRateLimit($this->throttleKey($input))) {
            return $this->receipt(self::RESULT_THROTTLED, $correlationId, 'Too many requests. Try again later.');
        }

        if ($this->honeypotFilled($input)) {
            // Accepted, and nothing written. Same shape as success on purpose.
            return $this->receipt(self::RESULT_ACCEPTED, $correlationId);
        }

        $errors = $this->validate($input);
        if ($errors !== []) {
            return $this->receipt(
                self::RESULT_INVALID,
                $correlationId,
                'Please correct the highlighted fields.',
                $errors
            );
        }

        $leadId = $this->persist($scope, $input, $correlationId);

        // Past this line the lead is durable. Everything below may fail without
        // costing the business the enquiry (LBR-5.1).
        $this->queueAnalysis($scope, $leadId, $input);

        return $this->receipt(self::RESULT_ACCEPTED, $correlationId);
    }

    /**
     * Writes the lead, its raw submission and its opening status-history row as
     * one unit, then commits.
     *
     * JOINING AN OUTER TRANSACTION: PDO/MySQL has no nested transactions, and
     * the test harness wraps every test in one. When a transaction is already
     * open this method takes part in it instead of calling beginTransaction()
     * and throwing - the atomicity guarantee is then the OUTER transaction's,
     * which is strictly no weaker. Only the owner commits or rolls back.
     *
     * @param  array<string, mixed> $input
     * @return int The generated lead id.
     */
    private function persist(TenantScope $scope, array $input, string $correlationId): int
    {
        $owns = !$this->pdo->inTransaction();
        if ($owns) {
            $this->pdo->beginTransaction();
        }

        try {
            $this->execute(
                'INSERT INTO leads (' . TenantScope::COLUMN . ', correlation_id, email, name, company,'
                . ' source, status, ip_hash)'
                . ' VALUES (:' . TenantScope::PARAM . ', :correlation_id, :email, :name, :company,'
                . ' :source, :status, :ip_hash)',
                $scope,
                [
                    'correlation_id' => $correlationId,
                    'email' => $this->text($input, 'email', self::MAX_EMAIL),
                    'name' => $this->text($input, 'name', self::MAX_NAME),
                    'company' => $this->nullableText($input, 'company', self::MAX_COMPANY),
                    'source' => $this->text($input, 'source', 64) !== ''
                        ? $this->text($input, 'source', 64)
                        : 'public_form',
                    'status' => self::STATUS_NEW,
                    'ip_hash' => $this->nullableText($input, 'ip_hash', 64),
                ]
            );

            $leadId = $this->lastInsertId();

            $this->execute(
                'INSERT INTO lead_submissions (' . TenantScope::COLUMN . ', lead_id, payload_json, ip_hash,'
                . ' user_agent)'
                . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :payload_json, :ip_hash, :user_agent)',
                $scope,
                [
                    'lead_id' => $leadId,
                    'payload_json' => $this->encode($this->submissionPayload($input)),
                    'ip_hash' => $this->nullableText($input, 'ip_hash', 64),
                    'user_agent' => $this->nullableText($input, 'user_agent', 255),
                ]
            );

            $this->recordStatus($scope, $leadId, null, self::STATUS_NEW, 'captured');

            if ($owns) {
                $this->pdo->commit();
            }

            return $leadId;
        } catch (Throwable $failure) {
            if ($owns && $this->pdo->inTransaction()) {
                $this->pdo->rollBack();
            }

            throw $failure;
        }
    }

    /**
     * Records the analysis as 'pending' and then hands the lead to the injected
     * analyzer, if there is one.
     *
     * The pending row is written FIRST and committed with nothing depending on
     * the analyzer, so an analyzer that dies mid-call - or a process killed
     * outright - still leaves a visible queue entry rather than a lead nobody
     * knows is waiting.
     *
     * @param array<string, mixed> $input
     */
    private function queueAnalysis(TenantScope $scope, int $leadId, array $input): void
    {
        $this->execute(
            'INSERT INTO lead_ai_analyses (' . TenantScope::COLUMN . ', lead_id, status)'
            . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :status)',
            $scope,
            ['lead_id' => $leadId, 'status' => 'pending']
        );

        $analysisId = $this->lastInsertId();

        if ($this->analyzer === null) {
            return;
        }

        try {
            $analysis = ($this->analyzer)($leadId, $this->analyzerView($input));

            $this->updateScoped(
                'lead_ai_analyses',
                ['status' => 'complete', 'analysis_json' => $this->encode($analysis)],
                $scope,
                $analysisId
            );
        } catch (Throwable $failure) {
            // LBR-5.1. The lead is already committed - the only thing left to
            // decide is who looks at it, and the answer is a human.
            $this->updateScoped(
                'lead_ai_analyses',
                [
                    'status' => 'failed',
                    'error_message' => mb_substr($failure->getMessage(), 0, 255),
                ],
                $scope,
                $analysisId
            );

            $this->updateScoped('leads', ['status' => self::STATUS_REVIEW], $scope, $leadId);
            $this->recordStatus($scope, $leadId, self::STATUS_NEW, self::STATUS_REVIEW, 'ai_analysis_failed');
        }
    }

    /**
     * @param array<string, scalar|null> $values
     */
    private function updateScoped(string $table, array $values, TenantScope $scope, int $id): void
    {
        $assignments = [];
        $params = ['row_id' => $id];

        foreach ($values as $column => $value) {
            // FR-TEN-001: the scope column is never writable, not even here
            // where every column name is a local constant.
            $scope->rejectTenantColumnWrite($column);

            $assignments[] = $column . ' = :' . $column;
            $params[$column] = $value;
        }

        $this->execute(
            'UPDATE ' . $this->identifier($table) . ' SET ' . implode(', ', $assignments)
            . $scope->where('id = :row_id'),
            $scope,
            $params
        );
    }

    private function recordStatus(
        TenantScope $scope,
        int $leadId,
        ?string $from,
        string $to,
        string $reason
    ): void {
        $this->execute(
            'INSERT INTO lead_status_history (' . TenantScope::COLUMN . ', lead_id, from_status, to_status, reason)'
            . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :from_status, :to_status, :reason)',
            $scope,
            [
                'lead_id' => $leadId,
                'from_status' => $from,
                'to_status' => $to,
                'reason' => $reason,
            ]
        );
    }

    /**
     * The single choke point: prepare, bind the caller's parameters, then let
     * TenantScope bind the tenant LAST and unconditionally.
     *
     * @param array<string, scalar|null> $params
     */
    private function execute(string $sql, TenantScope $scope, array $params): PDOStatement
    {
        $scope->rejectCallerBinding($params);

        $statement = $this->pdo->prepare($sql);
        if ($statement === false) {
            // Unreachable under ERRMODE_EXCEPTION, kept so a laxer PDO
            // configuration cannot turn a failed prepare into a silent no-op.
            throw new RuntimeException(sprintf('Failed to prepare statement: %s', $sql));
        }

        foreach ($params as $name => $value) {
            $statement->bindValue(':' . $name, $value, $this->pdoType($value));
        }

        $scope->bindTo($statement);
        $statement->execute();

        return $statement;
    }

    private function pdoType(bool|float|int|string|null $value): int
    {
        return match (true) {
            $value === null => PDO::PARAM_NULL,
            is_bool($value) => PDO::PARAM_BOOL,
            is_int($value) => PDO::PARAM_INT,
            default => PDO::PARAM_STR,
        };
    }

    private function lastInsertId(): int
    {
        $id = $this->pdo->lastInsertId();
        if ($id === false || !ctype_digit($id)) {
            // Surfaced rather than coerced to 0, which would hand the caller a
            // plausible-looking id pointing at nothing.
            throw new RuntimeException('The driver reported no generated key for the inserted lead row.');
        }

        return (int) $id;
    }

    /**
     * LFR-CAP-003, fail closed. A limiter that cannot be reached is treated as
     * a limiter that said no.
     */
    private function withinRateLimit(string $key): bool
    {
        try {
            return $this->rateLimiter->hit($key);
        } catch (Throwable $unreachable) {
            error_log('Lead capture rate limiter unavailable: ' . $unreachable->getMessage());

            return false;
        }
    }

    /**
     * The throttle identity. The controller supplies the HMAC of the client IP.
     * When it is absent every such request shares ONE bucket rather than each
     * getting its own - unattributable traffic is throttled collectively
     * instead of being handed an unlimited allowance.
     *
     * @param array<string, mixed> $input
     */
    private function throttleKey(array $input): string
    {
        $key = $this->text($input, 'ip_hash', 64);

        return $key !== '' ? $key : 'unattributed';
    }

    /**
     * @param array<string, mixed> $input
     */
    private function honeypotFilled(array $input): bool
    {
        return $this->text($input, self::HONEYPOT_FIELD, 255) !== '';
    }

    /**
     * @param  array<string, mixed> $input
     * @return array<string, string>
     */
    private function validate(array $input): array
    {
        $errors = [];

        if ($this->text($input, 'name', self::MAX_NAME) === '') {
            $errors['name'] = 'Name is required.';
        }

        $email = $this->text($input, 'email', self::MAX_EMAIL);
        if ($email === '' || filter_var($email, FILTER_VALIDATE_EMAIL) === false) {
            $errors['email'] = 'A valid email is required.';
        }

        if ($this->text($input, 'automation_need', self::MAX_NEED) === '') {
            $errors['automation_need'] = 'Workflow details are required.';
        }

        return $errors;
    }

    /**
     * The verbatim submission, minus the honeypot (which is noise) and minus
     * the derived ip_hash (which has its own column).
     *
     * @param  array<string, mixed> $input
     * @return array<string, string>
     */
    private function submissionPayload(array $input): array
    {
        $payload = [];

        foreach ($input as $field => $value) {
            if ($field === self::HONEYPOT_FIELD || $field === 'ip_hash') {
                continue;
            }

            if (is_scalar($value)) {
                $payload[$field] = mb_substr((string) $value, 0, self::MAX_NEED);
            }
        }

        return $payload;
    }

    /**
     * What the analyzer is allowed to see. A narrow, typed view rather than the
     * raw request array: the AI stage is the least trusted consumer here, so it
     * gets the parsed fields and nothing else.
     *
     * @param  array<string, mixed> $input
     * @return array<string, string|null>
     */
    private function analyzerView(array $input): array
    {
        return [
            'name' => $this->text($input, 'name', self::MAX_NAME),
            'email' => $this->text($input, 'email', self::MAX_EMAIL),
            'company' => $this->nullableText($input, 'company', self::MAX_COMPANY),
            'automation_need' => $this->text($input, 'automation_need', self::MAX_NEED),
        ];
    }

    /**
     * @param array<string, mixed> $values
     */
    private function encode(array $values): string
    {
        $json = json_encode($values, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        // json_encode returns false on malformed UTF-8 - storing "false" as a
        // JSON column value would fail at the database anyway, so say why here.
        return $json === false ? '{}' : $json;
    }

    /**
     * @param array<string, mixed> $input
     */
    private function text(array $input, string $field, int $maxLength): string
    {
        $value = $input[$field] ?? '';
        if (!is_scalar($value)) {
            return '';
        }

        return mb_substr(trim((string) $value), 0, $maxLength);
    }

    /**
     * @param array<string, mixed> $input
     */
    private function nullableText(array $input, string $field, int $maxLength): ?string
    {
        $value = $this->text($input, $field, $maxLength);

        return $value !== '' ? $value : null;
    }

    /**
     * The tenant arrives as a string from the transport layer. Anything that is
     * not a positive integer is refused HERE rather than being cast to 0 and
     * handed to TenantScope as "tenant zero".
     */
    private function tenantNumber(string $tenantId): ?int
    {
        $trimmed = trim($tenantId);

        return ctype_digit($trimmed) ? (int) $trimmed : null;
    }

    /**
     * Table names cannot be bound, so the two constants this class interpolates
     * are still checked - a repository has no reason to name a table with a
     * backtick or a semicolon in it.
     */
    private function identifier(string $name): string
    {
        if (preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $name) !== 1) {
            throw new RuntimeException(sprintf('Refusing to interpolate "%s" as a table name.', $name));
        }

        return $name;
    }

    /**
     * @param  array<string, string> $errors
     * @return array{status: int, correlation_id: string, message: string, errors: array<string, string>}
     */
    private function receipt(
        int $status,
        string $correlationId,
        string $message = self::RECEIPT,
        array $errors = []
    ): array {
        return [
            'status' => $status,
            'correlation_id' => $correlationId,
            'message' => $message,
            'errors' => $errors,
        ];
    }
}
