<?php

declare(strict_types=1);

namespace App\Leads;

use App\Tenancy\TenantScope;
use PDO;
use PDOStatement;
use RuntimeException;
use Throwable;

/**
 * Outbound messaging, tasks and human corrections for leads.
 *
 * This is the human-facing counterpart to LeadService's intake pipeline. It
 * never calls a real mailer/sms gateway - a "send" records a delivery row and
 * returns whether one was written, which is exactly what makes the send
 * observable and idempotent. The transport is a later concern; the guarantees
 * below are not.
 *
 * ALL tenant scoping goes through App\Tenancy\TenantScope, exactly like
 * LeadService: every statement is built from TenantScope::COLUMN / PARAM and
 * bound by bindTo(), so the predicate is generated by the same class the
 * repositories use and cannot be omitted or misspelled at a call site
 * (FR-TEN-002 / AC-001). Nothing here uses PDO::query or PDO::exec - that
 * would trip NoUnscopedClientQueryRule.
 *
 * © AI WebScapes 2026
 */
final class MessageService
{
    /** The acknowledgement kind. One per (tenant, lead) via a UNIQUE key. */
    private const KIND_ACK = 'acknowledgement';

    /** Bounded personalization tokens a template may carry (LBR-5.3). */
    private const TEMPLATE_TOKEN = '{{name}}';

    /**
     * Escalation keywords (LBR-5.6): complaints, legal and safety signals that
     * must route to a human rather than an automated reply. Allow-list - a
     * keyword added later is inert until listed here, the safe failure mode.
     *
     * @var list<string>
     */
    private const ESCALATION_KEYWORDS = [
        'lawyer',
        'legal',
        'lawsuit',
        'complaint',
        'complain',
        'sue',
        'safety',
        'danger',
        'urgent',
    ];

    /** A single escalation keyword is enough; the subject is the one to review. */
    private const MAX_NAME = 120;

    public function __construct(
        private PDO $pdo
    ) {
    }

    /**
     * Sends the seeded acknowledgement template to a lead.
     *
     * Idempotent (LFR-MSG-001): the UNIQUE (tenant, lead, kind) key means a
     * retry after a transient failure inserts nothing. Returns true iff THIS
     * call wrote a delivery row.
     *
     * Honours opt-out (LFR-MSG-002 / LBR-5.4): if the lead's email is on the
     * suppression list, no delivery is written and the method returns false.
     * The caller is told "not sent" rather than "sent" so the pipeline never
     * believes it contacted someone who asked not to be contacted.
     *
     * @param string      $tenantId The actor's tenant - the ONLY tenant whose
     *                              data this call may touch.
     * @param string|null $email    Override the recipient (defaults to the
     *                              lead's stored email). Used by tests; in
     *                              production the lead row supplies it.
     */
    public function sendAcknowledgement(int $leadId, string $tenantId, ?string $email = null): bool
    {
        $scope = new TenantScope($this->tenantNumber($tenantId));

        $recipient = $email ?? $this->leadEmail($scope, $leadId);
        if ($recipient === null || $this->isOptedOut($scope, $recipient)) {
            // Nothing written. A suppressed or unknown recipient cannot be
            // messaged, and the caller learns it was not sent.
            return false;
        }

        $body = $this->renderTemplate($scope, 'lead_ack', $recipient);
        if ($body === null) {
            // No template means nothing to send - fail closed to "not sent"
            // rather than inventing wording.
            return false;
        }

        return $this->recordDelivery($scope, $leadId, self::KIND_ACK, 'email', $recipient, 'lead_ack', $body);
    }

    /**
     * LFR-TASK-001. Opens a task against a lead. Tenant-scoped; a task opened
     * under one tenant is invisible to every other tenant's scoped reads.
     *
     * @return int|null The new task id, or null if the lead is not in scope.
     */
    public function createTask(int $leadId, string $tenantId, string $title, ?string $dueAt = null): ?int
    {
        $scope = new TenantScope($this->tenantNumber($tenantId));

        if (!$this->leadExists($scope, $leadId)) {
            return null;
        }

        $this->execute(
            'INSERT INTO lead_tasks (' . TenantScope::COLUMN . ', lead_id, title, status, due_at)'
            . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :title, :status, :due_at)',
            $scope,
            [
                'lead_id' => $leadId,
                'title' => mb_substr(trim($title), 0, 190),
                'status' => 'open',
                'due_at' => $dueAt,
            ]
        );

        $id = $this->lastInsertId();

        return is_numeric($id) ? (int) $id : null;
    }

    /**
     * LFR-DASH-004. Records a human correction of an AI-extracted field as an
     * APPEND-ONLY row. The original AI verdict is never rewritten - the method
     * only inserts into lead_field_corrections with both the old and new
     * values, so the model's first answer stays reconstructable forever.
     *
     * @param int         $leadId   The lead whose field is corrected.
     * @param string      $tenantId The actor's tenant.
     * @param string      $field    The corrected field name.
     * @param string      $newValue The human's value (stored verbatim).
     * @param int|null    $actorId  The human making the correction.
     */
    public function correctField(
        int $leadId,
        string $tenantId,
        string $field,
        string $newValue,
        ?int $actorId = null
    ): void {
        $scope = new TenantScope($this->tenantNumber($tenantId));

        $oldValue = $this->currentAIField($scope, $leadId, $field);

        $this->execute(
            'INSERT INTO lead_field_corrections (' . TenantScope::COLUMN
            . ', lead_id, field_name, old_value, new_value, corrected_by)'
            . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :field_name, :old_value, :new_value, :corrected_by)',
            $scope,
            [
                'lead_id' => $leadId,
                'field_name' => mb_substr(trim($field), 0, 64),
                'old_value' => $oldValue,
                'new_value' => mb_substr($newValue, 0, 65535),
                'corrected_by' => $actorId,
            ]
        );
    }

    /**
     * LBR-5.6. Pure, static: does the text carry an escalation keyword? Kept
     * static so controllers/tests can ask without a database.
     */
    public static function requiresEscalation(string $text): bool
    {
        $lower = mb_strtolower($text);

        foreach (self::ESCALATION_KEYWORDS as $keyword) {
            if (str_contains($lower, $keyword)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Returns true iff a delivery row for this (tenant, lead, kind) already
     * exists - the read half of the idempotency contract. Exposed for callers
     * that want to know up front, though sendAcknowledgement enforces it
     * structurally via the UNIQUE key regardless.
     */
    public function alreadySent(int $leadId, string $tenantId, string $kind = self::KIND_ACK): bool
    {
        $scope = new TenantScope($this->tenantNumber($tenantId));

        $statement = $this->execute(
            'SELECT id FROM message_deliveries ' . $scope->where('lead_id = :lead_id AND kind = :kind'),
            $scope,
            ['lead_id' => $leadId, 'kind' => $kind]
        );

        return is_numeric($statement->fetchColumn());
    }

    /**
     * The single SQL choke point, mirroring LeadService::execute(): prepare,
     * bind caller params, then bind the tenant LAST and unconditionally.
     *
     * @param array<string, scalar|null> $params
     */
    private function execute(string $sql, TenantScope $scope, array $params): PDOStatement
    {
        $scope->rejectCallerBinding($params);

        $statement = $this->pdo->prepare($sql);
        if ($statement === false) {
            throw new RuntimeException(sprintf('Failed to prepare statement: %s', $sql));
        }

        foreach ($params as $name => $value) {
            $statement->bindValue(':' . $name, $value, $this->pdoType($value));
        }

        $scope->bindTo($statement);
        $statement->execute();

        return $statement;
    }

    /**
     * Writes a delivery row, returning false (not throwing) when the UNIQUE
     * (tenant, lead, kind) key blocks a duplicate - that is the idempotent
     * retry path, not an error (LFR-MSG-001).
     */
    private function recordDelivery(
        TenantScope $scope,
        int $leadId,
        string $kind,
        string $channel,
        ?string $recipient,
        ?string $templateCode,
        string $body
    ): bool {
        try {
            $this->execute(
                'INSERT INTO message_deliveries (' . TenantScope::COLUMN
                . ', lead_id, kind, channel, recipient, template_code, body)'
                . ' VALUES (:' . TenantScope::PARAM . ', :lead_id, :kind, :channel, :recipient, :template_code, :body)',
                $scope,
                [
                    'lead_id' => $leadId,
                    'kind' => $kind,
                    'channel' => $channel,
                    'recipient' => $recipient,
                    'template_code' => $templateCode,
                    'body' => $body,
                ]
            );
        } catch (Throwable $duplicate) {
            // 23000 = SQLSTATE integrity constraint violation, i.e. the UNIQUE
            // key fired. That is the expected, intended outcome of a retried
            // send - not a failure to surface.
            if ($this->isUniqueViolation($duplicate)) {
                return false;
            }

            throw $duplicate;
        }

        return true;
    }

    private function isUniqueViolation(Throwable $failure): bool
    {
        // PDO maps the SQLSTATE into the driver-specific code; both are checked
        // so the test for idempotency is not brittle to how the exception is
        // read back.
        if (
            $failure instanceof \PDOException
            && (int) $failure->getCode() === 23000
        ) {
            return true;
        }

        $message = $failure->getMessage();

        return str_contains($message, 'Duplicate entry')
            || str_contains($message, '1062');
    }

    /**
     * Renders a seeded template with bounded personalization (LBR-5.3): only
     * the {{name}} token is substituted, from the lead's stored name. No other
     * token is recognised and no other field flows into the body, so the
     * personalization surface is exactly one value.
     */
    private function renderTemplate(TenantScope $scope, string $code, string $recipient): ?string
    {
        $statement = $this->execute(
            'SELECT body FROM message_templates ' . $scope->where('code = :code AND is_active = 1'),
            $scope,
            ['code' => $code]
        );

        $body = $statement->fetchColumn();
        if (!is_string($body)) {
            return null;
        }

        $name = $this->leadName($scope, $this->leadIdFromRecipient($scope, $recipient));

        return str_replace(self::TEMPLATE_TOKEN, $name ?? self::TEMPLATE_TOKEN, $body);
    }

    private function leadEmail(TenantScope $scope, int $leadId): ?string
    {
        $statement = $this->execute(
            'SELECT email FROM leads ' . $scope->where('id = :id'),
            $scope,
            ['id' => $leadId]
        );

        $value = $statement->fetchColumn();

        return is_string($value) ? $value : null;
    }

    private function leadName(TenantScope $scope, ?int $leadId): ?string
    {
        if ($leadId === null) {
            return null;
        }

        $statement = $this->execute(
            'SELECT name FROM leads ' . $scope->where('id = :id'),
            $scope,
            ['id' => $leadId]
        );

        $value = $statement->fetchColumn();

        return is_string($value) ? mb_substr($value, 0, self::MAX_NAME) : null;
    }

    private function leadIdFromRecipient(TenantScope $scope, string $recipient): ?int
    {
        $statement = $this->execute(
            'SELECT id FROM leads ' . $scope->where('email = :email'),
            $scope,
            ['email' => $recipient]
        );

        $value = $statement->fetchColumn();

        return is_numeric($value) ? (int) $value : null;
    }

    private function isOptedOut(TenantScope $scope, string $email): bool
    {
        $statement = $this->execute(
            'SELECT id FROM message_opt_outs ' . $scope->where('email = :email'),
            $scope,
            ['email' => mb_strtolower(trim($email))]
        );

        return is_numeric($statement->fetchColumn());
    }

    private function leadExists(TenantScope $scope, int $leadId): bool
    {
        $statement = $this->execute(
            'SELECT id FROM leads ' . $scope->where('id = :id'),
            $scope,
            ['id' => $leadId]
        );

        return is_numeric($statement->fetchColumn());
    }

    private function currentAIField(TenantScope $scope, int $leadId, string $field): ?string
    {
        // The most recent AI verdict's value for the field, if any.
        $statement = $this->execute(
            'SELECT analysis_json FROM lead_ai_analyses '
            . $scope->where('lead_id = :lead_id AND analysis_json IS NOT NULL')
            . ' ORDER BY id DESC LIMIT 1',
            $scope,
            ['lead_id' => $leadId]
        );

        $json = $statement->fetchColumn();
        if (!is_string($json)) {
            return null;
        }

        $value = json_decode($json, true);
        if (!is_array($value) || !array_key_exists($field, $value)) {
            return null;
        }

        return is_scalar($value[$field]) ? (string) $value[$field] : null;
    }

    private function lastInsertId(): string|false
    {
        return $this->pdo->lastInsertId();
    }

    private function pdoType(bool|float|int|string|null $value): int
    {
        return match (true) {
            $value === null => PDO::PARAM_NULL,
            is_bool($value) => PDO::PARAM_BOOL,
            is_int($value) => PDO::PARAM_INT,
            default => PDO::PARAM_STR,
        };
    }

    private function tenantNumber(string $tenantId): ?int
    {
        $trimmed = trim($tenantId);

        return ctype_digit($trimmed) ? (int) $trimmed : null;
    }
}
